data bye_house;
infile "C:\Users\user\Desktop\주택담보대출(고정형)_세로(2013~)_2.csv" dlm=',' dsd firstobs=2;
length date $7.;
input date : $7. interest;
run;
proc sgplot data=bye_house;
series x=date y=interest;
title "주택담보대출";
run;
proc arima data=bye_house;
identify var=interest nlag=24; run;
proc arima data=bye_house;
identify var=interest(1) nlag=24;
run;
proc arima data=bye_house;
identify var=interest(1,1) nlag=24;
run;
proc arima data=bye_house;
identify var=interest(1);
estimate q=1;
run;
/**선택모형**/
proc arima data=bye_house;
identify var=interest(1);
estimate q=1 noint;
run;
proc arima data=bye_house;
identify var=interest(1);
estimate p=1 noint;
run;
proc arima data=bye_house;
identify var=interest(1);
estimate p=1 q=1 noint;
run;
proc arima data=bye_house;
 identify var=interest(1);
 estimate q=1 noint;
 forecast lead=10 out=fore;
run;
data fore;
set fore; 
date=_n_; 
if z ne.then forecast.;
run;
proc sgplot;
series x=date y=interest;
xaxis values=(0 to 148 by 10) label="date";
yaxis label="Zt";
series x=date y=forecast /markers; run; 
proc arima data=bye_house;
    identify var=interest(1);
    estimate q=1 noint;
    forecast lead=10 out=fore;
run;
data fore2;
 set fore; 
date = intnx('month', '01JAN2013'd, _n_-1);
format date yymmn6.; 
if not missing(interest) then forecast = .;
run;
proc sgplot data=fore2;
    series x=date y=interest / lineattrs=(color=blue);
    series x=date y=forecast / markers lineattrs=(color=red thickness=2);
    xaxis label="날짜"  values=('01JAN2013'd to '01DEC2026'd by year);
    yaxis label="주택담보대출금리";
    title "ARIMA(0,1,1) 미래 예측값 시각화";
run;
