## Summary

> 22110670 김정운

| symbol | meaning          |
|:------:|:-----------------|
|   \+   | addition         |
|   \-   | subtraction      |
|   \*   | multiplication   |
|   /    | division         |
|   \^   | exponential      |
|   %%   | modulus          |
|  %/%   | integer division |

### Built-in function

-   sin(x)
-   cos(x)
-   tan(x)
-   exp(x)
-   log(x)
-   sqrt(x)
-   floor(x)
-   ceiling(x)
-   round(x)

### Variable

1.  Variable name must be made by english, number, `.`,`_`
2.  Seperate uppercase, lowercase
3.  In Variable name, `.`can be start but character must be behind

use(`()`), not only input also output can display

```         
(y \<- (1+1/x)\^x)
```

### Vector

-   seq : sequence
-   rep : repeat
-   c : combine

```         
(x <- seq(from=1, to=20, by=2))
(y <- rep(4,4))
(z <- c(y, x))
```

-   another methods for sequence

```         
x<-100:110
```

-   letters, LETTERS(each lowercase, uppercase) `letters, LETTERS`

-   seq_along(x)

    ```         
    x<-letters[1:5]
    y<-seq_along(x)
    print(y)
    ```

-   get element x[i]

    ```         
    x[2]
    x[length(x)] // extract last element
    ```

-   use element example

    ```         
    i <- c(1,3,2)
    x[i]  
    ```

> cf) minus index extract back elements(but not combine with plus)

> When apply an algebraic expression to two vectors of unequal length, R automatically repeats the shorter vector until it has something the same length as the longer vector.

```         
c(1,2,3,4) + c(1,2) 
c(1,2,3) + c(1,2)
```

> second one makes some error message

#### Logical vector

```         
logi <- c(TRUE, FALSE, T, F)
typeof(logi)
```

#### another things

-   char \<- c() : character
-   integ \<- c() :integer
-   doub \<- c() : double
-   as.character(double) : duble to character
-   as.numeric(c("num char","num char",...)) : character to double
-   as.integer(c("num char","num char",...)) : character to integer

#### Coercion

```         
logical, integer, double, character
```

> more flexible type go to right

#### Example :Mean, Variance

```         
mean(x)
x.mean <- sum(x)/length(x)
var(x)
x.var <- sum((x-x.man)^2)/(length(x)-1)
```

#### Example : simple numerical integration

```         
dt <- 0.005
t <- seq(0, pi/6, by = dt)
ft <- cos(t)

plot(t, ft, type = "n", xlab = "x", ylab = "f")

for (i in 1:(length(t) - 1)) {
  rect(t[i], 0, t[i] + dt, ft[i], col = "gray", border = "black")
}

(I <-sum(t) * dt)
```
#### Example : exponential limit

```         
n <- seq(10, 200, by=10)
y = (1+1/n)^n
exp(1)-y
```

```         
plot(n,y)
```

### Missing data

`is.na`
 
```         
a <- c(11, NA, 13)
is.na(a)
mean(a)
mean(a, na.rm = TURE) #NAs an be removed
```

### Inf and -Inf

> if value is too big, R print `Inf`

```         
- 2 ^ 1024
```

### NaN

> is there no mean of value, R print `NaN`

```         
Inf - Inf
0/0
```

### Subsetting

`x[subset]`

```         
x <- 1:10
x %% 4 == 0
(y <- x[x %% 4 == 0])
```

> subset() dismiss NA, x[subset] substain NA

```         
x <- c(1, NA, 3, 4)
x[x>2]
subset(x, subset = x>2)
```

> use `which(v)`,if you want TURE elements

```         
x <- c(1,1,2,3,5,8,13)
which(x %% 2 == 0)
```

### Sequential `&&` and `||`

> `&&`,`||` only work on scalars, whereas `&`,`|` work on vector on element by element basic

```         
x == 0 || sin(1/x) == 0
x == 0 | sin(1/x) == 0
c(TRUE, FALSE) & c(TRUE, TRUE)
c(TRUE, FALSE) && c(TRUE, TRUE)
```

### Names

```         
(x <- c(a = 1, b = 2, c = 3))
y <- 1:3
names(y) <- c("first", "second", "third")
```

### matrix

> `matrix(data, nrow = , ncol = , byrow = T/F)`



### Etc.

-   rounding error

```         
sqrt(2)*sqrt(2) == 2
all.equal(sqrt(2)*sqrt(2), 2)
```
